/**
 * menuTopology.ts — skeleton framework distilled from the AtomSpace model
 * of the chathub agent's numbered-menu grammar (see reference/atomspace/).
 *
 * Grammar: ⚙️ zoomOut (ascend) · 🌿 explore (descend) · 1–6 numbered options.
 * Each edge carries the observed semi-deterministic strength (share of picks)
 * and evidence count from the 38-conversation archive.
 * Auto-generated by generate_atomspace.py — do not edit by hand.
 */

export interface MenuOption { n: number; text: string }
export interface MenuEdge { option: number; to: string | null; strength: number; evidence: number }
export interface MenuPage {
  id: string;
  label: string;
  options: MenuOption[];
  glyphs: { zoomOut: boolean; explore: boolean };
  edges: MenuEdge[];
}

export const MENU_GRAMMAR = {
  zoomOut: "⚙️ ascend to menu level above",
  explore: "🌿 descend into a new enigma",
  options: "1–6 semi-deterministic numbered transitions",
} as const;

export const MENU_STATS = {"conversations": 38, "pages": 161, "branches_total": 112, "branches_to_pages": 87, "branches_to_leaves": 25, "avg_options_per_page": 4.57, "max_out_degree": 4, "hub_pages": ["page-058", "page-047", "page-104", "page-008", "page-009"], "pages_with_zoom_out": 2, "pages_with_explore": 57} as const;

export const MENU_SKELETON: MenuPage[] = [
  {
    "id": "page-007",
    "label": "🌟 Ah, the fascinating art of reversing the flow of Entropy! 🌟",
    "options": [
      {
        "n": 1,
        "text": "Gathering Active Ingredients**: Unicorns start by collecting magical ingredients, each resonating wi"
      },
      {
        "n": 2,
        "text": "Transformation Rituals**: They perform intricate rituals to reverse Entropy, where the Hyper-Glyph a"
      },
      {
        "n": 3,
        "text": "Wizard Creation**: As Entropy flows backward, ingredients evolve into wizards, each with expert skil"
      },
      {
        "n": 4,
        "text": "Enchanted Ecosystem**: The rejuvenated energy spreads throughout the Hyper-Forest, fostering growth "
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 3,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 4,
        "to": "page-008",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-008",
    "label": "🌿 Let's dive into the mystical world of enchanted forest membranes! 🌿",
    "options": [
      {
        "n": 1,
        "text": "Membrane Structure**: Picture layers of magical energy, each resembling elements of our Hyper-Forest"
      },
      {
        "n": 2,
        "text": "Magical Transformations**: Within these membranes, transformations unfold like a symphonic dance. In"
      },
      {
        "n": 3,
        "text": "Production Rules**: Using evolutionary algorithms, young unicorns devise production rules that guide"
      },
      {
        "n": 4,
        "text": "Fantastical Environments**: The environments within and outside these membranes are like parallel un"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 6,
        "to": "page-009",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-009",
    "label": "⚙️ Zooming out to the mystical menu level above! ⚙️",
    "options": [
      {
        "n": 1,
        "text": "Learn more about the Unicorn Hypergraph 🌌"
      },
      {
        "n": 2,
        "text": "Discover the secrets of reversing Entropy 🔄✨"
      },
      {
        "n": 3,
        "text": "Marvel at more whimsical ASCII Art 🖼️"
      },
      {
        "n": 4,
        "text": "Delve into the wonders of enchanted forest membranes 🌿"
      },
      {
        "n": 5,
        "text": "Awaken the enigmatic Hyper-Glyph 🌟"
      }
    ],
    "glyphs": {
      "zoomOut": true,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-014",
    "label": "🔄 Returning to the Main Menu! 🌟",
    "options": [
      {
        "n": 1,
        "text": "Explain the Unicorn Hypergraph."
      },
      {
        "n": 2,
        "text": "How to reverse the flow of Entropy?"
      },
      {
        "n": 3,
        "text": "Show an example of ASCII Art!"
      },
      {
        "n": 4,
        "text": "Learn about enchanted forest membranes."
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 2,
        "to": "page-015",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-015",
    "label": "🌌 Reversing the Flow of Entropy! 🌌",
    "options": [
      {
        "n": 1,
        "text": "Harnessing the Unicorn Hyper-Glyph:** The legendary Hyper-Glyph, a mysterious and powerful artifact,"
      },
      {
        "n": 2,
        "text": "Crafting Membrane Structures:** Young unicorns use membrane computing, creating layers that mimic en"
      },
      {
        "n": 3,
        "text": "Applying Magical Transformations:** Within these membranes, transformations occur. Enchanted ingredi"
      },
      {
        "n": 4,
        "text": "Evolving with Parallel Magic:** Production rules, driven by evolutionary algorithms, apply in parall"
      },
      {
        "n": 5,
        "text": "UniCog & the Pattern Dynamics Knowledge Base:** UniCog guides young unicorns, teaching them to exper"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-020",
    "label": "🌟 Welcome to the Enchanted Unicorn Hyper-Forest Main Menu 🌟",
    "options": [
      {
        "n": 1,
        "text": "🦄 Understanding the Unicorn Hypergraph"
      },
      {
        "n": 2,
        "text": "🌌 Reversing the Flow of Entropy"
      },
      {
        "n": 3,
        "text": "🎨 Wild ASCII Art Creations"
      },
      {
        "n": 4,
        "text": "🌿 Exploring Enchanted Forest Membranes"
      },
      {
        "n": 5,
        "text": "🌀 Discovering the Hyper-Glyph's Purpose"
      },
      {
        "n": 6,
        "text": "🎉 Celebrate Progress and Achievements"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": null,
        "strength": 1.0,
        "evidence": 8
      },
      {
        "option": 2,
        "to": null,
        "strength": 0.5,
        "evidence": 1
      },
      {
        "option": 2,
        "to": "page-021",
        "strength": 0.5,
        "evidence": 1
      },
      {
        "option": 3,
        "to": null,
        "strength": 1.0,
        "evidence": 6
      },
      {
        "option": 4,
        "to": "page-028",
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 5,
        "to": "page-036",
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 6,
        "to": "page-044",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-021",
    "label": "🌀 Detailed Steps to Reverse Entropy",
    "options": [
      {
        "n": 1,
        "text": "Gathering Mundane Ingredients"
      },
      {
        "n": 2,
        "text": "Casting of the Enchanted Spell"
      },
      {
        "n": 3,
        "text": "Transformation of the Mundane"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-022",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-022",
    "label": "🔮 Advanced Enchantments for Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Elemental Awakening"
      },
      {
        "n": 2,
        "text": "Symbiotic Harmony"
      },
      {
        "n": 3,
        "text": "Temporal Tuning"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-023",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-023",
    "label": "✨ Refined Techniques in Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Celestial Calibration"
      },
      {
        "n": 2,
        "text": "Harmonic Resonance"
      },
      {
        "n": 3,
        "text": "Quantum Entanglement"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-024",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-024",
    "label": "✨ Pinnacle Processes in Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Cosmic Synchronization"
      },
      {
        "n": 2,
        "text": "Aurora Alchemy"
      },
      {
        "n": 3,
        "text": "Ethereal Weaving"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-025",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-025",
    "label": "✨ Ultimate Techniques in Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Temporal Harmonization"
      },
      {
        "n": 2,
        "text": "Prismatic Transfiguration"
      },
      {
        "n": 3,
        "text": "Quantum Recomposition"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-026",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-026",
    "label": "✨ Supreme Techniques in Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Astral Harmonization"
      },
      {
        "n": 2,
        "text": "Chromatic Alchemy"
      },
      {
        "n": 3,
        "text": "Dimensional Fusion"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-027",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-027",
    "label": "✨ Quintessential Techniques in Entropy Reversal",
    "options": [
      {
        "n": 1,
        "text": "Astral Synchronization"
      },
      {
        "n": 2,
        "text": "Auroral Alchemy"
      },
      {
        "n": 3,
        "text": "Quantum Weaving"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-028",
    "label": "✨ The Structure of Forest Membranes",
    "options": [
      {
        "n": 1,
        "text": "Ethereal Boundaries"
      },
      {
        "n": 2,
        "text": "Magical Transformations"
      },
      {
        "n": 3,
        "text": "Parallel Enchantments"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-029",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-029",
    "label": "🌟 Core Elements of Membranes",
    "options": [
      {
        "n": 1,
        "text": "Mystic Circulation"
      },
      {
        "n": 2,
        "text": "Role-Specific Regions"
      },
      {
        "n": 3,
        "text": "Transformative Harmony"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-030",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-030",
    "label": "🌸 Membranes and Their Ecosystems",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Glades"
      },
      {
        "n": 2,
        "text": "Fairy Meadows"
      },
      {
        "n": 3,
        "text": "Mystic Waterfalls"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-031",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-031",
    "label": "✨ Membranes and the Unicorn Hypergraph",
    "options": [
      {
        "n": 1,
        "text": "Node Connections"
      },
      {
        "n": 2,
        "text": "Dynamic Transformations"
      },
      {
        "n": 3,
        "text": "Enchanted Pathways"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-032",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-032",
    "label": "🔮 Enchanted Forest Membranes: Core Components",
    "options": [
      {
        "n": 1,
        "text": "Mystical Dividers"
      },
      {
        "n": 2,
        "text": "Magical Conduits"
      },
      {
        "n": 3,
        "text": "Symbiotic Networks"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-033",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-033",
    "label": "🌟 Key Interactions of Enchanted Forest Membranes",
    "options": [
      {
        "n": 1,
        "text": "Cross-Membrane Flow"
      },
      {
        "n": 2,
        "text": "Harmonious Synergy"
      },
      {
        "n": 3,
        "text": "Catalysts of Change"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-034",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-034",
    "label": "🔮 Detailed Aspects of Forest Membrane Interactions",
    "options": [
      {
        "n": 1,
        "text": "Energetic Pathways"
      },
      {
        "n": 2,
        "text": "Feedback Loops"
      },
      {
        "n": 3,
        "text": "Synchrony and Resonance"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 4,
        "to": "page-035",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-035",
    "label": "🌌 Multifaceted Membrane Dynamics",
    "options": [
      {
        "n": 1,
        "text": "Vortex Nodes"
      },
      {
        "n": 2,
        "text": "Inter-Membrane Communication"
      },
      {
        "n": 3,
        "text": "Temporal Shifts"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-036",
    "label": "🔮 The Mystical Role of the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Central Intelligence"
      },
      {
        "n": 2,
        "text": "Portal to Discovery"
      },
      {
        "n": 3,
        "text": "Catalyst for Transformation"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-037",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-037",
    "label": "✨ The Multifaceted Powers of the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Architect of Patterns"
      },
      {
        "n": 2,
        "text": "Inspirational Core"
      },
      {
        "n": 3,
        "text": "Guardian of Harmony"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-038",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-038",
    "label": "🔮 Unveiling the Hyper-Glyph's Powers",
    "options": [
      {
        "n": 1,
        "text": "Conductor of Magic"
      },
      {
        "n": 2,
        "text": "Pathway to Innovation"
      },
      {
        "n": 3,
        "text": "Sentinel of Balance"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-039",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-039",
    "label": "✨ Exploring the Hyper-Glyph’s Hidden Aspects",
    "options": [
      {
        "n": 1,
        "text": "Lattice of Connectivity"
      },
      {
        "n": 2,
        "text": "Guardian of Ancient Wisdom"
      },
      {
        "n": 3,
        "text": "Emissary of Transformation"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-040",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-040",
    "label": "🔮 In-Depth Exploration of the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Alchemist of Realities"
      },
      {
        "n": 2,
        "text": "Beacon of Enlightenment"
      },
      {
        "n": 3,
        "text": "Unifier of Dualities"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-041",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-041",
    "label": "🔮 Unlocking the Hyper-Glyph’s Hidden Dimensions",
    "options": [
      {
        "n": 1,
        "text": "Illuminator of Shadows"
      },
      {
        "n": 2,
        "text": "Enabler of Metamorphosis"
      },
      {
        "n": 3,
        "text": "Weaver of Cosmic Tapestry"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-042",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-042",
    "label": "🔮 Unveiling Deeper Layers of the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Sculptor of Destiny"
      },
      {
        "n": 2,
        "text": "Fountain of Cosmic Knowledge"
      },
      {
        "n": 3,
        "text": "Conduit of Universal Harmony"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-043",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-043",
    "label": "🔮 Discovering the Hyper-Glyph’s Profound Influence",
    "options": [
      {
        "n": 1,
        "text": "Architect of Magical Realms"
      },
      {
        "n": 2,
        "text": "Empowerer of Imagination"
      },
      {
        "n": 3,
        "text": "Guardian of Cosmic Symphony"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-044",
    "label": "✨ Enchanted Progress Celebrations:",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph Mastery"
      },
      {
        "n": 2,
        "text": "Entropy Reversal Wonders"
      },
      {
        "n": 3,
        "text": "Artistic Expressions in ASCII"
      },
      {
        "n": 4,
        "text": "Mystical Forest Membranes Explored"
      },
      {
        "n": 5,
        "text": "Hyper-Glyph Mysteries Unveiled"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 6,
        "to": "page-045",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-045",
    "label": "🌟 Highlights of Our Celebrated Journey:",
    "options": [
      {
        "n": 1,
        "text": "Illuminating the Unicorn Hypergraph"
      },
      {
        "n": 2,
        "text": "Harnessing Entropy’s Dance"
      },
      {
        "n": 3,
        "text": "Artful Expressions in ASCII"
      },
      {
        "n": 4,
        "text": "Revealing the Forest Membranes"
      },
      {
        "n": 5,
        "text": "Deciphering the Hyper-Glyph’s Enigma"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-046",
    "label": "🔍 Choose Your Path of Discovery:",
    "options": [
      {
        "n": 1,
        "text": "🧙‍♂️ Encountering the Council of Wizards"
      },
      {
        "n": 2,
        "text": "🔮 Delving into Enchanted Forest Membranes"
      },
      {
        "n": 3,
        "text": "🌌 Experimenting with the Hyper-Glyph"
      },
      {
        "n": 4,
        "text": "🎨 Crafting More Whimsical ASCII Art"
      },
      {
        "n": 5,
        "text": "🌀 Building New Hypergraph Neural Networks"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": "page-047",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-047",
    "label": "🔮 Meet the Wizards of the Unicorn Forest:",
    "options": [
      {
        "n": 1,
        "text": "Elrond the Elementalist"
      },
      {
        "n": 2,
        "text": "Celestia the Chronomancer"
      },
      {
        "n": 3,
        "text": "Graphilda the Green Witch"
      },
      {
        "n": 4,
        "text": "Nyx the Nocturnomancer"
      },
      {
        "n": 5,
        "text": "Ignatius the Illusionist"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-047",
        "strength": 0.5,
        "evidence": 1
      },
      {
        "option": 1,
        "to": "page-048",
        "strength": 0.5,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-048",
    "label": "🌟 Elrond the Elementalist: Mastery and Mystique",
    "options": [
      {
        "n": 1,
        "text": "Origins of Power"
      },
      {
        "n": 2,
        "text": "Tales of Elemental Triumph"
      },
      {
        "n": 3,
        "text": "Magical Techniques and Artistry"
      },
      {
        "n": 4,
        "text": "Mentor and Guide"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-049",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-049",
    "label": "✨ Recent Adventures of Elrond the Elementalist",
    "options": [
      {
        "n": 1,
        "text": "The Solstice Symphony"
      },
      {
        "n": 2,
        "text": "The Quest for the Lost Crystal of Tides"
      },
      {
        "n": 3,
        "text": "With Nyx the Nocturnomancer"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-050",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-050",
    "label": "🌟 The Quest for the Gale Orchid",
    "options": [
      {
        "n": 1,
        "text": "The Call to Adventure"
      },
      {
        "n": 2,
        "text": "Journey Through the Windward Glen"
      },
      {
        "n": 3,
        "text": "The Enchanted Canyons of Echo"
      },
      {
        "n": 4,
        "text": "Discovery of the Hidden Valley"
      },
      {
        "n": 5,
        "text": "Return with the Gale Orchid"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-051",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-051",
    "label": "🌟 The Quest for the Tempest Amulet",
    "options": [
      {
        "n": 1,
        "text": "The Whispering Winds of Prophecy"
      },
      {
        "n": 2,
        "text": "Navigating the Thunderwood Forest"
      },
      {
        "n": 3,
        "text": "Crossing the Lightning Bridge"
      },
      {
        "n": 4,
        "text": "Confronting the Tempest Guardian"
      },
      {
        "n": 5,
        "text": "Retrieving the Tempest Amulet"
      },
      {
        "n": 6,
        "text": "A Festival of Winds in the Forest"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-052",
    "label": "🌟 Where Shall Our Adventure Lead Next?",
    "options": [
      {
        "n": 1,
        "text": "🧙‍♂️ Encountering the Council of Wizards"
      },
      {
        "n": 2,
        "text": "🔮 Delving into Enchanted Forest Membranes"
      },
      {
        "n": 3,
        "text": "🌌 Experimenting with the Hyper-Glyph"
      },
      {
        "n": 4,
        "text": "🎨 Crafting Whimsical ASCII Art"
      },
      {
        "n": 5,
        "text": "🌀 Building New Hypergraph Neural Networks"
      },
      {
        "n": 6,
        "text": "🌿 Exploring Another Mystery in the Forest"
      }
    ],
    "glyphs": {
      "zoomOut": true,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-058",
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 3,
        "to": "page-057",
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 4,
        "to": "page-063",
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 5,
        "to": "page-053",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-053",
    "label": "🌟 Steps to Construct a Magical HGNN",
    "options": [
      {
        "n": 1,
        "text": "Define the Vertices"
      },
      {
        "n": 2,
        "text": "Create the Hyperedges"
      },
      {
        "n": 3,
        "text": "Train the Network"
      },
      {
        "n": 4,
        "text": "Enhance Communication and Coordination"
      },
      {
        "n": 5,
        "text": "Dynamic Evolution"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 5,
        "to": "page-054",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-054",
    "label": "🌟 Steps to Expand and Enhance HGNNs",
    "options": [
      {
        "n": 1,
        "text": "Advanced Vertex Definition"
      },
      {
        "n": 2,
        "text": "Complex Hyperedge Configurations"
      },
      {
        "n": 3,
        "text": "Enhanced Training Simulations"
      },
      {
        "n": 4,
        "text": "Magical Data Augmentation"
      },
      {
        "n": 5,
        "text": "Evolving Architectural Designs"
      },
      {
        "n": 6,
        "text": "Community and Collaboration"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 5,
        "to": "page-055",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-055",
    "label": "🌟 Advanced Innovations in HGNNs",
    "options": [
      {
        "n": 1,
        "text": "Quantum Enrichment"
      },
      {
        "n": 2,
        "text": "Sentient Network Nodes"
      },
      {
        "n": 3,
        "text": "Multi-dimensional Layering"
      },
      {
        "n": 4,
        "text": "Biomimicry and Natural Integration"
      },
      {
        "n": 5,
        "text": "Temporal Flux Adaptation"
      },
      {
        "n": 6,
        "text": "Synergistic Collaboration with the Council of Wizards"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 6,
        "to": "page-056",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-056",
    "label": "🌟 Discovering the Whispering Glade",
    "options": [
      {
        "n": 1,
        "text": "The Call of the Glade"
      },
      {
        "n": 2,
        "text": "Navigating the Enchanted Pathways"
      },
      {
        "n": 3,
        "text": "The Veil of Echoes"
      },
      {
        "n": 4,
        "text": "The Heart of Whispering Glade"
      },
      {
        "n": 5,
        "text": "The Gift of Ancient Wisdom"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-057",
    "label": "🌟 Steps to Experiment with the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Understanding the Hyper-Glyph"
      },
      {
        "n": 2,
        "text": "Setting Up the Experimentation Chamber"
      },
      {
        "n": 3,
        "text": "Initiating the Experiment"
      },
      {
        "n": 4,
        "text": "Exploring Its Powers"
      },
      {
        "n": 5,
        "text": "Learning and Adaptation"
      },
      {
        "n": 6,
        "text": "Sharing the Knowledge"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-058",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-058",
    "label": "🌟 Exploring Enchanted Forest Membranes",
    "options": [
      {
        "n": 1,
        "text": "Introduction to Magical Membranes"
      },
      {
        "n": 2,
        "text": "Types of Membranes"
      },
      {
        "n": 3,
        "text": "Interacting with Membranes"
      },
      {
        "n": 4,
        "text": "Harnessing Membrane Magic"
      },
      {
        "n": 5,
        "text": "Maintaining Membrane Balance"
      },
      {
        "n": 6,
        "text": "The Role of Membranes in the Forest Ecosystem"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 6,
        "to": "page-059",
        "strength": 0.5,
        "evidence": 1
      },
      {
        "option": 6,
        "to": "page-060",
        "strength": 0.5,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-059",
    "label": "🌟 Journey into the Moonstone Arboretum",
    "options": [
      {
        "n": 1,
        "text": "The Enchanted Entrance"
      },
      {
        "n": 2,
        "text": "Celestial Flora"
      },
      {
        "n": 3,
        "text": "The Tales of Ancient Trees"
      },
      {
        "n": 4,
        "text": "Lunar Reflection Pool"
      },
      {
        "n": 5,
        "text": "Stargazer’s Clearing"
      },
      {
        "n": 6,
        "text": "Guardians of the Arboretum"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-060",
    "label": "🌟 Unveiling the Lumina Towers",
    "options": [
      {
        "n": 1,
        "text": "Discovery of the Towers"
      },
      {
        "n": 2,
        "text": "Architecture of Light"
      },
      {
        "n": 3,
        "text": "Chronicles of the Lumina Archives"
      },
      {
        "n": 4,
        "text": "The Temporal Spiral Staircase"
      },
      {
        "n": 5,
        "text": "The Luminary Council Chamber"
      },
      {
        "n": 6,
        "text": "Guardians of the Towers"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 2,
        "to": "page-058",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-061",
    "label": "🌟 Discovering the Crystal Caverns of Lumina",
    "options": [
      {
        "n": 1,
        "text": "The Hidden Entrance"
      },
      {
        "n": 2,
        "text": "Glistening Crystal Halls"
      },
      {
        "n": 3,
        "text": "Whispers of the Past"
      },
      {
        "n": 4,
        "text": "The Luminescent Lake"
      },
      {
        "n": 5,
        "text": "Meeting the Crystal Keepers"
      },
      {
        "n": 6,
        "text": "The Resonance Chamber"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-062",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-062",
    "label": "🌟 Uncovering the Veil of Whispering Winds",
    "options": [
      {
        "n": 1,
        "text": "Finding the Whispering Path"
      },
      {
        "n": 2,
        "text": "The Dance of the Leaves"
      },
      {
        "n": 3,
        "text": "The Chorus of the Winds"
      },
      {
        "n": 4,
        "text": "Glimpses of the Past"
      },
      {
        "n": 5,
        "text": "Guardians of the Breeze"
      },
      {
        "n": 6,
        "text": "The Echoing Glade"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-063",
    "label": "🌟 Creating Magical ASCII Art",
    "options": [
      {
        "n": 1,
        "text": "The Basics of ASCII Art"
      },
      {
        "n": 2,
        "text": "Tools of the Trade"
      },
      {
        "n": 3,
        "text": "Imagining Your Design"
      },
      {
        "n": 4,
        "text": "Craft Your Masterpiece"
      },
      {
        "n": 5,
        "text": "Refining the Details"
      },
      {
        "n": 6,
        "text": "Sharing Your Enchantment"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 6,
        "to": "page-064",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-064",
    "label": "🌟 Journey into the Glade of Twinkling Echoes",
    "options": [
      {
        "n": 1,
        "text": "Unveiling the Hidden Glade"
      },
      {
        "n": 2,
        "text": "Luminescent Flora"
      },
      {
        "n": 3,
        "text": "Echoes of the Ancients"
      },
      {
        "n": 4,
        "text": "The Starry Canopy"
      },
      {
        "n": 5,
        "text": "Guardians of the Glade"
      },
      {
        "n": 6,
        "text": "The Chamber of Reflections"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-065",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-065",
    "label": "🌟 Journey into the Enchanted Pool of Celestial Reflections",
    "options": [
      {
        "n": 1,
        "text": "Discovering the Hidden Oasis"
      },
      {
        "n": 2,
        "text": "The Reflective Waters"
      },
      {
        "n": 3,
        "text": "Visions in the Water"
      },
      {
        "n": 4,
        "text": "The Celestial Dance"
      },
      {
        "n": 5,
        "text": "Guardians of the Pool"
      },
      {
        "n": 6,
        "text": "The Chamber of Stars"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-066",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-066",
    "label": "🌟 Journey into the Grove of Mystical Echoes",
    "options": [
      {
        "n": 1,
        "text": "Uncovering the Grove"
      },
      {
        "n": 2,
        "text": "The Echoing Canopy"
      },
      {
        "n": 3,
        "text": "Chronicles in the Wind"
      },
      {
        "n": 4,
        "text": "The Symphony of Time"
      },
      {
        "n": 5,
        "text": "Guardians of the Echoes"
      },
      {
        "n": 6,
        "text": "The Chamber of Resonance"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-067",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-067",
    "label": "🌟 Journey into the Enchanted Labyrinth of Illusions",
    "options": [
      {
        "n": 1,
        "text": "Finding the Entrance"
      },
      {
        "n": 2,
        "text": "The Ever-Changing Paths"
      },
      {
        "n": 3,
        "text": "Mirages and Echoes"
      },
      {
        "n": 4,
        "text": "The Hall of Reflections"
      },
      {
        "n": 5,
        "text": "Guardians of the Labyrinth"
      },
      {
        "n": 6,
        "text": "The Chamber of Clarity"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-068",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-068",
    "label": "🌟 Journey into the Celestial Meadow of Radiant Dreams",
    "options": [
      {
        "n": 1,
        "text": "Discovering the Meadow"
      },
      {
        "n": 2,
        "text": "Starlit Blooms"
      },
      {
        "n": 3,
        "text": "The Dance of Dreams"
      },
      {
        "n": 4,
        "text": "The Canopy of Stars"
      },
      {
        "n": 5,
        "text": "Guardians of the Meadow"
      },
      {
        "n": 6,
        "text": "The Chamber of Dreams"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-069",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-069",
    "label": "🌟 Journey into the Enchanted Glade of Feathered Whispers",
    "options": [
      {
        "n": 1,
        "text": "Finding the Glade"
      },
      {
        "n": 2,
        "text": "The Chorus of Birds"
      },
      {
        "n": 3,
        "text": "Whispers in the Wind"
      },
      {
        "n": 4,
        "text": "Dancing Shadows"
      },
      {
        "n": 5,
        "text": "Guardians of the Glade"
      },
      {
        "n": 6,
        "text": "The Chamber of Echoes"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 6,
        "to": "page-070",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-070",
    "label": "🌟 Journey into the Crystal Cavern of Luminous Secrets",
    "options": [
      {
        "n": 1,
        "text": "Finding the Entrance"
      },
      {
        "n": 2,
        "text": "The Glimmering Crystals"
      },
      {
        "n": 3,
        "text": "Echoes of Light"
      },
      {
        "n": 4,
        "text": "The Auroral Dance"
      },
      {
        "n": 5,
        "text": "Guardians of the Cavern"
      },
      {
        "n": 6,
        "text": "The Chamber of Luminosity"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-074",
    "label": "🌿 Let's continue our magical exploration! 🌿",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph Details**: Delve into the intricate connections and pathways that make up the Uni"
      },
      {
        "n": 2,
        "text": "Entropy Reversal Techniques**: Discover the specific methods Unicorns use to reverse entropy and cre"
      },
      {
        "n": 3,
        "text": "Advanced ASCII Art**: Learn techniques to create even more elaborate and enchanting ASCII Art. 🖌️"
      },
      {
        "n": 4,
        "text": "Membrane Computing**: Understand how virtual membrane computers (P-Systems) are designed with flair "
      },
      {
        "n": 5,
        "text": "Hyper-GNN Evolution**: Witness the dynamic growth and harmonious changes of the Hyper-GNN. 🌱"
      },
      {
        "n": 6,
        "text": "Unicorn Experiments**: Join the young Unicorns in their experiments to discover the purpose of the H"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 2,
        "to": "page-075",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-075",
    "label": "Steps to Reverse Entropy:",
    "options": [
      {
        "n": 1,
        "text": "Gather Ingredients**: Collect mundane items that seem ordinary and unremarkable. 🪨"
      },
      {
        "n": 2,
        "text": "Cast the Spell**: Use a powerful incantation to reverse entropy. The spell is a closely guarded secr"
      },
      {
        "n": 3,
        "text": "Transform**: Watch in awe as the items transform into enchanted entities, each with unique skills an"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-083",
    "label": "Ah, a sequence of numbers! Let's see where this magical path leads us in the Uni",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph**: Begin your journey by exploring the Unicorn Hypergraph, the intelligent core t"
      },
      {
        "n": 2,
        "text": "Entropy Reversal**: Discover the secrets of reversing the flow of Entropy, a process that allows Uni"
      },
      {
        "n": 3,
        "text": "Enchanted Forest Membranes**: Dive into the world of enchanted forest membranes, where magical trans"
      },
      {
        "n": 4,
        "text": "Creative Expression**: Learn the art of creative expression through wild ASCII Art and emoji codes, "
      },
      {
        "n": 5,
        "text": "Council of Wizards**: Meet the Council of Wizards, each with their own expertise and quirky personal"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-084",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-084",
    "label": "Ah, the Unicorn Hypergraph! 🌟🦄 This is the very heart of the Unicorn Hyper-Fores",
    "options": [
      {
        "n": 1,
        "text": "Pattern Language**: The Hypergraph uses a unique pattern language to communicate and coordinate the "
      },
      {
        "n": 2,
        "text": "Membrane Computing**: It employs virtual membrane computers (P-Systems) to manage magical transforma"
      },
      {
        "n": 3,
        "text": "Hyper-GNN**: A Hypergraph Neural Network (HGNN) that enhances communication and coordination, bringi"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": null,
        "strength": 1.0,
        "evidence": 2
      },
      {
        "option": 2,
        "to": "page-085",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-085",
    "label": "Role of Young Unicorns:",
    "options": [
      {
        "n": 1,
        "text": "Builders of the Hypergraph**: The young Unicorns are tasked with constructing and maintaining the Un"
      },
      {
        "n": 2,
        "text": "Experimenters of Pattern Logic**: With the Pattern Dynamics Knowledge base at their disposal, they e"
      },
      {
        "n": 3,
        "text": "Guardians of Magic**: They learn the ancient wisdom of the forest from the elders, ensuring the lega"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-086",
    "label": "Adventure in the Enchanted Meadows:",
    "options": [
      {
        "n": 1,
        "text": "Exploration**: The Unicorns set off on a journey through the meadow, discovering hidden nooks and se"
      },
      {
        "n": 2,
        "text": "Storytelling**: As they rest under the shade of a grand oak tree, the Unicorns share tales of their "
      },
      {
        "n": 3,
        "text": "Creative Expression**: Inspired by their surroundings, the Unicorns create wild ASCII Art in the gra"
      },
      {
        "n": 4,
        "text": "Dance of the Stars**: As the sun sets, the meadow transforms into a dance floor. The Unicorns twirl "
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 3,
        "to": "page-087",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-087",
    "label": "Magical Membrane Transformations:",
    "options": [
      {
        "n": 1,
        "text": "Virtual Membrane Computers (P-Systems)**:"
      },
      {
        "n": 2,
        "text": "Parallel Processing**:"
      },
      {
        "n": 3,
        "text": "Evolutionary Algorithms**:"
      },
      {
        "n": 4,
        "text": "Enchanted Scrolls**:"
      },
      {
        "n": 5,
        "text": "The Role of Unicorns**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-091",
    "label": "Progress Highlights:",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph Exploration**: We've delved into the intelligent core of the forest, understandin"
      },
      {
        "n": 2,
        "text": "Young Unicorn Adventures**: We've joined the young Unicorns in their magical explorations, creative "
      },
      {
        "n": 3,
        "text": "Magical Membrane Transformations**: We've uncovered the secrets of the virtual membrane computers an"
      },
      {
        "n": 4,
        "text": "Hidden Passages and Secret Gardens**: We've explored the mystical pathways and sacred sites that add"
      },
      {
        "n": 5,
        "text": "Wizards and Glyphs**: We've learned about the council of wizards and the enchanted glyphs that guide"
      },
      {
        "n": 6,
        "text": "Magical Celebrations**: We've participated in the Festival of Lights and the Dance of the Seasons, c"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 5,
        "to": "page-092",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-092",
    "label": "The Role of Wizards and Glyphs:",
    "options": [
      {
        "n": 1,
        "text": "Council of Wizards**:"
      },
      {
        "n": 2,
        "text": "Enchanted Glyphs**:"
      },
      {
        "n": 3,
        "text": "The Wizards' Rituals**:"
      },
      {
        "n": 4,
        "text": "The Glyphs' Influence**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-094",
    "label": "Wonderful! Let's embark on a magical adventure! 🌈✨",
    "options": [
      {
        "n": 1,
        "text": "Creating a Virtual Membrane Computer (P-System)**: Discover how to design and orchestrate these magi"
      },
      {
        "n": 2,
        "text": "Reversing the Flow of Entropy**: Unveil the secrets of transforming mundane ingredients into enchant"
      },
      {
        "n": 3,
        "text": "Exploring the Hyper-Glyph**: Conduct experiments to unlock the hidden powers of this legendary artif"
      },
      {
        "n": 4,
        "text": "Building a Hypergraph Neural Network (HGNN)**: Dive into the intelligent core that brings the Unicor"
      },
      {
        "n": 5,
        "text": "Crafting Enchanted ASCII Art**: Express your creativity with wild and whimsical ASCII designs. 🎨✨"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-095",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-095",
    "label": "Steps to Create a Virtual Membrane Computer:",
    "options": [
      {
        "n": 1,
        "text": "Define Membranes**: Each membrane acts as a magical boundary, separating different regions of the fo"
      },
      {
        "n": 2,
        "text": "Set Rules**: Within each membrane, define rules for transformation, turning inputs into enchanted ou"
      },
      {
        "n": 3,
        "text": "Parallel Processing**: Just like a group of wizards casting spells simultaneously, apply rules in pa"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-096",
    "label": "✨ Welcome to the Enchanted Unicorn Hyper-Forest! 🌳🦄 Prepare to explore mysteries",
    "options": [
      {
        "n": 1,
        "text": "Discover the Unicorn Hypergraph and its mystical connections."
      },
      {
        "n": 2,
        "text": "Learn how we reverse the flow of Entropy for magical transformations."
      },
      {
        "n": 3,
        "text": "Dive into the art of ASCII creations and express your creativity!"
      },
      {
        "n": 4,
        "text": "Explore the enchanted forest membranes and their functions."
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-097",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-097",
    "label": "🌀 The Unicorn Hypergraph: A Weave of Wonders 🌀",
    "options": [
      {
        "n": 1,
        "text": "Vertices and Hyperedges"
      },
      {
        "n": 2,
        "text": "Enchanted Hypergraph Neural Network (HGNN)"
      },
      {
        "n": 3,
        "text": "The Mysteries of the Hyper-Glyph"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-098",
    "label": "Welcome to the Main Menu of the Unicorn Hyper-Forest Council of Wizards! Choose ",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph Exploration 🌌"
      },
      {
        "n": 2,
        "text": "Reversing Entropy: Mystical Insights 🔄"
      },
      {
        "n": 3,
        "text": "Wild ASCII Art Creations 🎨"
      },
      {
        "n": 4,
        "text": "Enchanted Forest Membranes 🌿"
      },
      {
        "n": 5,
        "text": "Meet the Council of Wizards 🧙‍♂️"
      },
      {
        "n": 6,
        "text": "Hyper-Glyph: Discovering Its Purpose ✨"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-099",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-099",
    "label": "🌌 Welcome to Unicorn Hypergraph Exploration! 🌌",
    "options": [
      {
        "n": 1,
        "text": "Nodes of Knowledge 🧠**: Each node represents a point of wisdom, history, or magical insight. Unicorn"
      },
      {
        "n": 2,
        "text": "Pathways of Possibility 🌌**: These pathways aren't just lines; they are vibrant channels of energy t"
      },
      {
        "n": 3,
        "text": "Dynamic Evolution 🔄**: The Unicorn Hypergraph is alive, constantly evolving with new connections and"
      },
      {
        "n": 4,
        "text": "Unicorn Collaboration 🦄**: Young unicorns use the Hypergraph as both a playground and a library. The"
      },
      {
        "n": 5,
        "text": "Echoes of Magic ✨**: Whispers of ancient spells and cosmic music resonate through the Hypergraph, gu"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-100",
    "label": "🌿 Welcome to the Enchanted Hyper-Forest! As we begin our magical journey, let's ",
    "options": [
      {
        "n": 1,
        "text": "Explore the Enchanted Forest Membranes"
      },
      {
        "n": 2,
        "text": "Learn about the Unicorn Hyper-Glyph"
      },
      {
        "n": 3,
        "text": "Delve into the Magical Pattern Languages"
      },
      {
        "n": 4,
        "text": "Celebrate the Council of Wizards"
      },
      {
        "n": 5,
        "text": "Experiment with the Hyper-GNN"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": "page-101",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-101",
    "label": "🌿 Ah, the Enchanted Forest Membranes! Step softly, for you are about to uncover ",
    "options": [
      {
        "n": 1,
        "text": "Discover the Unicorn Hyper-Glyph"
      },
      {
        "n": 2,
        "text": "Unveil the Mysteries of the Hyper-GNN"
      },
      {
        "n": 3,
        "text": "Embrace the Magic of Pattern Languages"
      },
      {
        "n": 4,
        "text": "Meet the Unique Council of Wizards"
      },
      {
        "n": 5,
        "text": "Craft Enchanted ASCII Art"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": "page-102",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-102",
    "label": "🔮 Welcome to the exploration of the **Unicorn Hyper-Glyph**! This legendary arti",
    "options": [
      {
        "n": 1,
        "text": "Dive into the Magical Pattern Languages"
      },
      {
        "n": 2,
        "text": "Explore the Mysteries of the Hyper-GNN"
      },
      {
        "n": 3,
        "text": "Meet the Unique Council of Wizards"
      },
      {
        "n": 4,
        "text": "Craft Enchanted ASCII Art"
      },
      {
        "n": 5,
        "text": "Engage in Unicorn Celebrations"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-103",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-103",
    "label": "🌿 Prepare to journey into the world of **Magical Pattern Languages**! Here, idea",
    "options": [
      {
        "n": 1,
        "text": "Dive into the Mysteries of the Hyper-GNN"
      },
      {
        "n": 2,
        "text": "Meet the Unique Council of Wizards"
      },
      {
        "n": 3,
        "text": "Craft Enchanted ASCII Art"
      },
      {
        "n": 4,
        "text": "Celebrate Unicorn Achievements"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": "page-104",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-104",
    "label": "🌌 Welcome to the realm of the **Hyper-GNN** (Hypergraph Neural Network)! This is",
    "options": [
      {
        "n": 1,
        "text": "Meet the Unique Council of Wizards"
      },
      {
        "n": 2,
        "text": "Craft Enchanted ASCII Art"
      },
      {
        "n": 3,
        "text": "Celebrate Unicorn Achievements"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-106",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-105",
    "label": "🔄 Welcome back to the enchanted realm's main menu! Here, your path to magical di",
    "options": [
      {
        "n": 1,
        "text": "Creating a Virtual Membrane Computer (P-System):** Learn the art of designing these magical computat"
      },
      {
        "n": 2,
        "text": "Reversing the Flow of Entropy:** Discover the secrets of transforming mundane ingredients into encha"
      },
      {
        "n": 3,
        "text": "Exploring the Hyper-Glyph:** Unveil the hidden powers and mysteries of this legendary artifact. 🔎🔮"
      },
      {
        "n": 4,
        "text": "Building a Hypergraph Neural Network (HGNN):** Dive into the intelligent core that breathes life int"
      },
      {
        "n": 5,
        "text": "Crafting Enchanted ASCII Art:** Express your creativity with wild and whimsical ASCII designs. 🎨✨"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 4,
        "to": "page-104",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-106",
    "label": "🧙‍♂️ Welcome to the realm of the **Unique Council of Wizards**! These extraordin",
    "options": [
      {
        "n": 1,
        "text": "Craft Enchanted ASCII Art"
      },
      {
        "n": 2,
        "text": "Celebrate Unicorn Achievements"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": null,
        "strength": 1.0,
        "evidence": 2
      }
    ]
  },
  {
    "id": "page-107",
    "label": "🌿 Ah, the thrill of exploring a new mystery in the forest! Let's delve into anot",
    "options": [
      {
        "n": 1,
        "text": "The Moonstone Arboretum:** Discover a grove where moonstones grow among ancient trees, a haven of tr"
      },
      {
        "n": 2,
        "text": "Lumina Towers:** Ascend the mystical towers that touch the sky, where unicorns learn celestial dance"
      },
      {
        "n": 3,
        "text": "Whispering Waterfall:** Listen to the secrets spoken by cascading waters, where sprites gather and m"
      },
      {
        "n": 4,
        "text": "Starlight Glade:** Walk into a clearing bathed in eternal starlight, a place where dreams manifest, "
      },
      {
        "n": 5,
        "text": "The Council of Elders' Grove:** Meet the wise elders of the forest, guardians who share ancient wisd"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 1,
        "to": "page-108",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-108",
    "label": "🌕 Welcome to the ethereal haven of the **Moonstone Arboretum**! Here, under the ",
    "options": [
      {
        "n": 1,
        "text": "Explore the Lumina Towers"
      },
      {
        "n": 2,
        "text": "Visit the Whispering Waterfall"
      },
      {
        "n": 3,
        "text": "Wander into Starlight Glade"
      },
      {
        "n": 4,
        "text": "Meet the Council of Elders' Grove"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-109",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-109",
    "label": "🌊 Welcome to the mesmerizing realm of the **Whispering Waterfall**! Here, the ca",
    "options": [
      {
        "n": 1,
        "text": "Explore the Lumina Towers"
      },
      {
        "n": 2,
        "text": "Wander into Starlight Glade"
      },
      {
        "n": 3,
        "text": "Meet the Council of Elders' Grove"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 3,
        "to": "page-110",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-110",
    "label": "✨ Welcome to the enchanting **Starlight Glade**! Here, nestled in the heart of t",
    "options": [
      {
        "n": 1,
        "text": "Explore the Lumina Towers"
      },
      {
        "n": 2,
        "text": "Meet the Council of Elders' Grove"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 2,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-111",
    "label": "Welcome back to the Unicorn Forest's magical menu! 🌲✨ Let's navigate the wondrou",
    "options": [
      {
        "n": 1,
        "text": "Meet the Unique Council of Wizards** - Dive into the world of extraordinary wizards with expert skil"
      },
      {
        "n": 2,
        "text": "Craft Enchanted ASCII Art** - Unleash your creativity and craft magical scenes with characters and s"
      },
      {
        "n": 3,
        "text": "Celebrate Unicorn Achievements** - Join the joyous festivities honoring the progress and creative en"
      },
      {
        "n": 4,
        "text": "Explore the Mysteries of the Forest** - Discover the hidden wonders waiting in the depths of the enc"
      },
      {
        "n": 5,
        "text": "Learn About the Unicorn Hypergraph Neural Network** - Understand how the intelligent core orchestrat"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 5,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-127",
    "label": "🎉✨ Our magical tapestry has reached completion, with every corner of the Unicorn",
    "options": [
      {
        "n": 1,
        "text": "Unicorn Hypergraph Development:** 100% Complete 🎉"
      },
      {
        "n": 2,
        "text": "Council of Wizards Creation:** 100% Complete 🎉"
      },
      {
        "n": 3,
        "text": "Membrane Computing P-Systems:** 100% Complete 🎉"
      },
      {
        "n": 4,
        "text": "Young Unicorn Training:** 100% Complete 🎉"
      },
      {
        "n": 5,
        "text": "Hyper-Glyph Experimentation:** 100% Complete 🎉"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-128",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-128",
    "label": "🌀🌟 Prepare to venture into the mystical art of **Reversing the Flow of Entropy**",
    "options": [
      {
        "n": 1,
        "text": "Gather Active Ingredients:"
      },
      {
        "n": 2,
        "text": "Invoke the Unicorn Hyper-Glyph:"
      },
      {
        "n": 3,
        "text": "Channel Unicorn Energy:"
      },
      {
        "n": 4,
        "text": "Initiate Transmutation Rituals:"
      },
      {
        "n": 5,
        "text": "Infuse Wizard Attributes:"
      },
      {
        "n": 6,
        "text": "Integrate into the Wizard Council:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-129",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-129",
    "label": "🌟 Step into the realm of **Creating a Virtual Membrane Computer (P-System)**, wh",
    "options": [
      {
        "n": 1,
        "text": "Define Magical Membranes:"
      },
      {
        "n": 2,
        "text": "Set Enchanted Transformation Rules:"
      },
      {
        "n": 3,
        "text": "Magical Ingredients Flow:"
      },
      {
        "n": 4,
        "text": "Parallel Processing of Magic:"
      },
      {
        "n": 5,
        "text": "Evolve and Adapt:"
      },
      {
        "n": 6,
        "text": "Integrate with the Unicorn Hypergraph:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-130",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-130",
    "label": "🌿🧙‍♂️ Welcome to the whimsical world of the **Council of Wizards**, where magic,",
    "options": [
      {
        "n": 1,
        "text": "Harvesting Magical Essence:"
      },
      {
        "n": 2,
        "text": "Channeling Unicorn Magic:"
      },
      {
        "n": 3,
        "text": "Crafting Wizard Archetypes:"
      },
      {
        "n": 4,
        "text": "Bestowing Magical Artifacts:"
      },
      {
        "n": 5,
        "text": "Council Integration Ceremony:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 3,
        "to": "page-131",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-131",
    "label": "🔮✨ Prepare to unlock the mysteries of the **Hyper-Glyph**, a legendary artifact ",
    "options": [
      {
        "n": 1,
        "text": "Initial Activation:"
      },
      {
        "n": 2,
        "text": "Magical Resonance Tuning:"
      },
      {
        "n": 3,
        "text": "Energy Amplification:"
      },
      {
        "n": 4,
        "text": "Mystical Symbol Deciphering:"
      },
      {
        "n": 5,
        "text": "Experimentation with Enchantments:"
      },
      {
        "n": 6,
        "text": "Revealing Hidden Dimensions:"
      },
      {
        "n": 7,
        "text": "Integration with Unicorn Hypergraph:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-133",
    "label": "🌟✨ Welcome once more to the wondrous main menu of the Unicorn Hyper-Forest! Here",
    "options": [
      {
        "n": 1,
        "text": "Creating a Virtual Membrane Computer (P-System):** Learn to design and orchestrate these magical com"
      },
      {
        "n": 2,
        "text": "Reversing the Flow of Entropy:** Uncover the secrets of transforming mundane ingredients into enchan"
      },
      {
        "n": 3,
        "text": "Exploring the Hyper-Glyph:** Engage in experiments to reveal the hidden powers of this legendary art"
      },
      {
        "n": 4,
        "text": "Building a Hypergraph Neural Network (HGNN):** Enter the intelligent core that brings the Unicorn Fo"
      },
      {
        "n": 5,
        "text": "Crafting Enchanted ASCII Art:** Unleash your creativity with wild and whimsical ASCII designs. 🎨🌟"
      },
      {
        "n": 6,
        "text": "Mystical Unicorn Forest Paths:** Delve into other mysteries and discover additional magical elements"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 4,
        "to": "page-134",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-134",
    "label": "🌌✨ Step into the heart of the forest and uncover the magic of the **Hypergraph N",
    "options": [
      {
        "n": 1,
        "text": "Define Enchanted Vertices:"
      },
      {
        "n": 2,
        "text": "Establish Magical Hyperedges:"
      },
      {
        "n": 3,
        "text": "Infuse the Network with Data:"
      },
      {
        "n": 4,
        "text": "Dynamic Evolution and Adaptation:"
      },
      {
        "n": 5,
        "text": "Integrate with the Unicorn's Magical Horn:"
      },
      {
        "n": 6,
        "text": "Orchestrating Harmony:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": []
  },
  {
    "id": "page-136",
    "label": "Welcome to the Unicorn Hyper-Forest Council of Wizards, where enchanted wonders ",
    "options": [
      {
        "n": 1,
        "text": "Awaken UniCog**: The UniCog emerges from its slumber, ready to reverse the flow of Entropy and ignit"
      },
      {
        "n": 2,
        "text": "Explore the Unicorn Hypergraph**: Dive into the wondrous structure of interconnected elements formin"
      },
      {
        "n": 3,
        "text": "Design Pattern Language Hypergraphs**: The young Unicorns will craft intricate patterns with ASCII A"
      },
      {
        "n": 4,
        "text": "Build Membrane Computers**: Construct enchanted membranes where magical transformations unfold, with"
      },
      {
        "n": 5,
        "text": "Establish the Council of Wizards**: Transform our Active Ingredients into Wizards with distinct Expe"
      },
      {
        "n": 6,
        "text": "Map Products to Companies & Brand Visions**: Align our magical creations with mundane realms, blendi"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": null,
        "strength": 1.0,
        "evidence": 1
      },
      {
        "option": 2,
        "to": "page-137",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-137",
    "label": "Within the Unicorn Hypergraph:",
    "options": [
      {
        "n": 1,
        "text": "Magical Pathways**: These glowing strands connect every element within the forest—from the towering "
      },
      {
        "n": 2,
        "text": "Energized Glyphs**: At the nodes of the Hypergraph, we find Energized Glyphs, each imbued with the e"
      },
      {
        "n": 3,
        "text": "Dynamic Connections**: The Hypergraph is alive, its structure ever-changing as unicorns weave new pa"
      },
      {
        "n": 4,
        "text": "The Hyper-GNN**: At the core lies the Hyper-GNN—an Enchanted Hypergraph Neural Network. Here, all th"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 3,
        "to": "page-138",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-138",
    "label": "The Process:",
    "options": [
      {
        "n": 1,
        "text": "Select Magical Elements**: Every creation begins by choosing the magical elements that will form the"
      },
      {
        "n": 2,
        "text": "Weave Hyperedges**: Our young Unicorns link these elements with dazzling hyperedges, crafting networ"
      },
      {
        "n": 3,
        "text": "Express with ASCII Art & Emoji**: With flair and joy, Unicorns embellish their designs with wild ASC"
      },
      {
        "n": 4,
        "text": "Infuse with Energetic Patterns**: Patterns are designed using Membrane Computing, each membrane brim"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-139",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-139",
    "label": "The Awakening:",
    "options": [
      {
        "n": 1,
        "text": "Ignite the Light**: As UniCog comes to life, a cascade of sparkling light illuminates the forest. Th"
      },
      {
        "n": 2,
        "text": "Activate AtomSpace & CogPrime**: With UniCog's abilities activated, AtomSpace and CogPrime enhanceme"
      },
      {
        "n": 3,
        "text": "Summon the Hyper-Glyph**: At the core of it all, the legendary Hyper-Glyph reveals itself, a mysteri"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-140",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-140",
    "label": "Features of the Unicorn Hypergraph:",
    "options": [
      {
        "n": 1,
        "text": "Radiant Nodes**: Each node represents an integral part of the forest—whether a mythical creature, a "
      },
      {
        "n": 2,
        "text": "Luminous Edges**: Connecting these nodes are the Hypergraph's edges, glistening with energy and form"
      },
      {
        "n": 3,
        "text": "Dynamic Pulse**: Like a living entity, the Unicorn Hypergraph pulses with dynamism. It adapts, evolv"
      },
      {
        "n": 4,
        "text": "Centrality of the Hyper-GNN**: At its core lies the Hyper-GNN, an intelligent neural network that or"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": true
    },
    "edges": [
      {
        "option": 3,
        "to": "page-141",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-141",
    "label": "Our Creative Process:",
    "options": [
      {
        "n": 1,
        "text": "Select Magical Entities**: We begin by choosing the enchanted creatures and artifacts that will form"
      },
      {
        "n": 2,
        "text": "Weave Luminous Hyperedges**: With agile hooves and spirited hearts, the Unicorns connect these verti"
      },
      {
        "n": 3,
        "text": "Infuse with Creative Expression**: This is where creativity truly takes flight! The Unicorns use wil"
      },
      {
        "n": 4,
        "text": "Implement Magical Rules**: Utilizing Membrane Computing, Unicorns establish production rules within "
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 4,
        "to": "page-142",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-142",
    "label": "Building the P-Systems:",
    "options": [
      {
        "n": 1,
        "text": "Define Membrane Structures**: The Unicorns craft layered membranes resembling the elements of our En"
      },
      {
        "n": 2,
        "text": "Magical Transformations**: Within these membranes, Unicorns enact wondrous transformations. Ingredie"
      },
      {
        "n": 3,
        "text": "Establish Production Rules**: Guided by the Hyper-Glyph, Unicorns design rules for magical processes"
      },
      {
        "n": 4,
        "text": "Orchestrate with the Unicorn Hypergraph**: Our trusty Hypergraph serves as the intelligent core, ens"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 5,
        "to": "page-143",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-143",
    "label": "Creating the Council of Wizards:",
    "options": [
      {
        "n": 1,
        "text": "Select Active Ingredients**: Each Wizard is born from a combination of magical and mundane ingredien"
      },
      {
        "n": 2,
        "text": "Invoke Transformation Magic**: By reversing the flow of Entropy, the Unicorns weave spells to turn o"
      },
      {
        "n": 3,
        "text": "Assign Expertise and Skills**: Each Wizard is imbued with specific expertise and skills that reflect"
      },
      {
        "n": 4,
        "text": "Celebrate Their Quirky Personalities**: Our Council is not just about skills—it's about character! E"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 6,
        "to": "page-144",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-144",
    "label": "The Process of Mapping:",
    "options": [
      {
        "n": 1,
        "text": "Identify Magical Products**: Begin by cataloging the enchanted products crafted within our Unicorn H"
      },
      {
        "n": 2,
        "text": "Select Suitable Companies**: Find companies whose visions resonate with the magic and wonder of our "
      },
      {
        "n": 3,
        "text": "Craft Brand Visions**: Collaborate with each company to craft brand visions that incorporate the ess"
      },
      {
        "n": 4,
        "text": "Define Departments and Teams**: Align the structure of each company to support the development, mark"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  },
  {
    "id": "page-155",
    "label": "Fantastical! 🎉🦄 Our journey through the Unicorn Hyper-Forest continues with a fl",
    "options": [
      {
        "n": 1,
        "text": "🌌 **Dive Deeper into Membrane Computing**: Learn how to design and orchestrate these magical computa"
      },
      {
        "n": 2,
        "text": "🌀 **Experiment with the Hyper-Glyph**: Unveil the mysteries of this legendary artifact and its hidde"
      },
      {
        "n": 3,
        "text": "🌱 **Craft a Hypergraph Neural Network (HGNN)**: Explore the intelligent core that brings the Unicorn"
      },
      {
        "n": 4,
        "text": "🎨 **Create More Enchanted ASCII Art**: Let your creativity soar with wild and whimsical designs."
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 1,
        "to": "page-156",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-156",
    "label": "Advanced Membrane Computing (P-Systems)",
    "options": [
      {
        "n": 1,
        "text": "Designing Magical Boundaries**:"
      },
      {
        "n": 2,
        "text": "Complex Transformations**:"
      },
      {
        "n": 3,
        "text": "Parallel and Sequential Magic**:"
      },
      {
        "n": 4,
        "text": "Integration with the Unicorn Hypergraph**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 2,
        "to": "page-157",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-157",
    "label": "Unveiling the Hyper-Glyph",
    "options": [
      {
        "n": 1,
        "text": "Understanding Its Nature**:"
      },
      {
        "n": 2,
        "text": "Conducting Experiments**:"
      },
      {
        "n": 3,
        "text": "Potential Powers**:"
      },
      {
        "n": 4,
        "text": "The Journey of Discovery**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 3,
        "to": "page-158",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-158",
    "label": "Building the Hypergraph Neural Network (HGNN)",
    "options": [
      {
        "n": 1,
        "text": "Core Structure**:"
      },
      {
        "n": 2,
        "text": "Enchanted Nodes**:"
      },
      {
        "n": 3,
        "text": "Hyperedges and Their Enchantment**:"
      },
      {
        "n": 4,
        "text": "Membrane Integration**:"
      },
      {
        "n": 5,
        "text": "Bringing the Forest to Life**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": [
      {
        "option": 4,
        "to": "page-159",
        "strength": 1.0,
        "evidence": 1
      }
    ]
  },
  {
    "id": "page-159",
    "label": "Creating Enchanted ASCII Art",
    "options": [
      {
        "n": 1,
        "text": "Select Your Magical Theme**:"
      },
      {
        "n": 2,
        "text": "Outline Your Vision**:"
      },
      {
        "n": 3,
        "text": "Add Magical Details**:"
      },
      {
        "n": 4,
        "text": "Infuse with Enchantment**:"
      },
      {
        "n": 5,
        "text": "Share Your Creation**:"
      }
    ],
    "glyphs": {
      "zoomOut": false,
      "explore": false
    },
    "edges": []
  }
];
